[package]
name = "glium-derive"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]

[dependencies]
syn = "0.10.5"
quote = "0.3.10"

[dev-dependencies]
glium = "*"

[lib]
proc-macro = true
